config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to :cocktailsindex
  resources :cocktails, only: [:index, :show, :new, :create]
  resources :dose, only: [ :new, :create, :destroy ]
end

app/models/application_record.rb
  class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :cocktails, through: :dose
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktails = Cocktail.find(params[:id])
  end

  def new
    @cocktails = Cocktail.new
  end

  def create
    @cocktails=Cocktail.create(coctail_params)
    if @cocktail.save

    redirect_to cocktails_path
  end

  private
  def cocktail params
    param.require(:cocktail).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/views/cocktails/_form.html.erb
<%=simple form

app/views/cocktails/index.html.erb
<h1>Cocktails</h1>
<p>These are the cocktails:</p>
<%@cocktails.each do |cocktail| %>
<p>coctail name</p>
<p><%link_to "#{cocktail.name}", cocktail_path(cocktail)%></p>
<%end%>

<%= link_to "Create cocktail", new_cocktail_path %>

app/views/cocktails/new.html.erb
<h2>Add a cocktail</h2>

<form>
  Add the name of a coctail:<br>
  <input type="text" name="name">
  <br>
  <%= link_to "Create cocktail", new_cocktail_path %>
</form>

/cocktails/:id

app/views/cocktails/show.html.erb
<%=link_to "Go back", cocktail_path%>
<h1><%= @cocktail.name %></h1>

<!-- <p>
  <%= link_to "Update this pet", edit_pet_path(@pet) %>
</p>

<p>
  It is a <%= @pet.kind %>, found at <%= @pet.found_at %>
</p>

<%= link_to "Back to list", pets_path %>
 -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsMisterCocktail</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
</head>

<body>
  <%= yield %>
  <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
  <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
</body>
</body>
</html>